[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["mkdir -p storage/pdf storage/tmp logs"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
